server:
  port: 80
  
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: scott
    password: sa
    
  jpa:
    database: oracle
    hibernate:
      ddl-auto: update

    show-sql: true



