server:
  port: 80
  
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.1.108:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: scott
    password: tiger
    
  jpa:
    database: oracle
    hibernate:
      ddl-auto: update
    show-sql: true